version: "1.0.0"
services:
  python-server:
    build: .
    depends_on:
      - mysql-db
    ports:
      - "1234:80"
    links:
      - mysql-db
  mysql-db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=4444
      - MYSQL_DATABASE=bd_crud
    volumes:
      - mysql-data:/var/lib/mysql/data
volumes:
  mysql-data:
